# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4346c2b842e7c84b9357aa56d8c4a9522fd803820fcde02fa8e553fb835611f4010d39f660ff6aa8197d4217112efc4a0b0325590c320e56b4e4befdc99319f4

test:
  secret_key_base: ddfeecf5052be83a39384345c42d42b179f26fd01acdb7e1817d9ad9099d56c30659f2be3bfd1d96ed4efddd1c2f5fec9eb3c2de7166834260db9079f2df8697

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
